spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reviews
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect